# Nomme ton projet ! Les noms de projet doivent contenir uniquement des
# caractères minuscules et des underscores. Un bon nom de package reflète
# le nom de ton organisation ou l'usage prévu de ces modèles.
name: 'dbt_ecommerce'
version: '1.0.0'

# Ce paramètre indique quel "profil" dbt utilise pour ce projet.
profile: 'dbt_ecommerce'

# Ces configurations précisent où dbt doit chercher les différents types de fichiers.
# Par exemple, `model-paths` indique que les modèles de ce projet se trouvent
# dans le dossier "models/". Tu n'auras probablement pas besoin de changer ça !
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # dossiers supprimés par la commande `dbt clean`
  - "target"
  - "dbt_packages"


# Configuration des modèles
# Documentation complète : https://docs.getdbt.com/docs/configuring-models

# Ici, on indique à dbt de matérialiser tous les modèles présents dans le
# dossier models/staging/ sous forme de vues (views). Ce paramètre peut être
# surchargé au cas par cas dans chaque fichier de modèle via la macro
# `{{ config(...) }}`.
models:
  dbt_ecommerce:
    staging:
      +materialized: view
    silver:
      +materialized: table